appName: notification-service
replicaCount: 1
isConsumer: false
appType: api
appProbe: true
appScript: "./server.sh"
appImage: stonetech66/micro-ride
appVersion: notification-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: REDIS_HOST
  value: "redis-notification-service:6379"
- name: NOTIFICATION_SERVICE_HOST
  value: "notification-service:8000"
- name: VERIFY_TOKEN_URL
  value: "user-account-service:8000/api/v1/verify-token"
- name: MONGO_HOST
  value: mongo-notification-service
- name: MONGO_PORT
  value: "27017"
secrets: 
- name: rabbitmq
- name: mongo-notification-service
- name: notification-service