appName: notification-service
replicaCount: 1
isConsumer: false
appType: api
appProbe: true
appScript: "./server.sh"
appImage: stonetech66/micro-ride
appVersion: notification-service
containerEnvVars:
- name: ROOT_PATH
  value: /notification-service
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: RABBITMQ_DEFAULT_USER
  value: guest
- name: RABBITMQ_DEFAULT_PASS
  value: guest
- name: REDIS_HOST
  value: "redis-notification-service:6379"
- name: NOTIFICATION_SERVICE_HOST
  value: "notification-service:8000/notification"
- name: VERIFY_TOKEN_URL
  value: "http://user-account-service:8000/api/v1/verify-token"
- name: MONGO_HOST
  value: mongo-notification-service-mongodb
- name: MONGO_PORT
  value: "27017"
- name: MONGO_ROOT_USERNAME
  value: root
otherSecrets:
- name: MONGO_ROOT_PASSWORD
  secretName: mongo-notification-service-mongodb
  secretKey: mongodb-root-password
- name: WEBSOCKET_SECRET_KEY
  secretName: notification-service
  secretKey: WEBSOCKET_SECRET_KEY
