appName: ride-service
replicaCount: 1
isConsumer: false
appType: api
appProbe: true
appScript: "./server.sh"
appImage: stonetech66/micro-ride
appVersion: ride-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: POSTGRES_HOST
  value: postgres-ride-service
- name: POSTGRES_PORT
  value: "5432"
- name: REDIS_HOST
  value: "redis-ride-service:6379"
- name: VERIFY_TOKEN_URL
  value: "user-account-service:8000/api/v1/verify-token"
- name: NOTIFICATION_SERVICE_HOST
  value: "notification-service:8000"
secrets: 
- name: postgres-ride-service
- name: rabbitmq
