appName: user-account-service
replicaCount: 1
isConsumer: false
appType: api
appProbe: true
appScript: "./server.sh"
appImage: stonetech66/micro-ride
appVersion: user-account-service
otherSecrets:
- name: POSTGRES_PASSWORD
  secretName: postgres-user-account-service-postgresql
  secretKey: postgres-password
containerEnvVars:
- name: ROOT_PATH
  value: /users
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: RABBITMQ_DEFAULT_USER
  value: guest
- name: RABBITMQ_DEFAULT_PASS
  value: guest
- name: POSTGRES_HOST
  value: postgres-user-account-service-postgresql
- name: POSTGRES_USER
  value: postgres
- name: POSTGRES_DB
  value: postgres
- name: POSTGRES_PORT
  value: "5432"
- name: REDIS_HOST
  value: "redis-user-account-service:6379"
appSecret:
- key: SECRET_KEY
  value: IHN0b25l

