appName: driver-service
replicaCount: 1
isConsumer: true
appType: consumer
appScript: "./consumer.sh"
appImage: stonetech66/micro-ride
appVersion: driver-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: RABBITMQ_DEFAULT_USER
  value: guest
- name: RABBITMQ_DEFAULT_PASS
  value: guest
- name: REDIS_HOST
  value: "redis-driver-service:6379"
- name: POSTGRES_HOST
  value: postgres-driver-service-postgresql
- name: POSTGRES_USER
  value: postgres
- name: POSTGRES_DB
  value: postgres
- name: POSTGRES_PORT
  value: "5432"
otherSecrets:
- name: POSTGRES_PASSWORD
  secretName: postgres-driver-service-postgresql
  secretKey: postgres-password
