appName: notification-service
replicaCount: 1
isConsumer: true
appType: consumer
appScript: "./consumer.sh"
appImage: stonetech66/micro-ride
appVersion: notification-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: REDIS_HOST
  value: "redis-notification-service:6379"
- name: NOTIFICATION_SERVICE_HOST
  value: "notification-service:8000"
- name: VERIFY_TOKEN_URL
  value: "user-account-service:8000"
appSecret:
- key: WEBSOCKET_SECRET_KEY
  value: IHN0b25l
secrets: 
- name: rabbitmq