appName: payment-service
replicaCount: 1
isConsumer: true
appType: consumer
appScript: "./consumer.sh"
appImage: stonetech66/micro-ride
appVersion: payment-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: RABBITMQ_DEFAULT_USER
  value: guest
- name: RABBITMQ_DEFAULT_PASS
  value: guest
- name: POSTGRES_HOST
  value: postgres-payment-service-postgresql
- name: POSTGRES_USER
  value: postgres
- name: POSTGRES_DB
  value: postgres
- name: POSTGRES_PORT
  value: "5432"
- name: REDIS_URL
  value: "redis-payment-service:6379"
- name: NOTIFICATION_SERVICE_HOST
  value: "notification-service:8000"
otherSecrets:
- name: POSTGRES_PASSWORD
  secretName: postgres-payment-service-postgresql
  secretKey: postgres-password
