appName: payment-service
replicaCount: 1
isConsumer: true
appType: consumer
appScript: "./consumer.sh"
appImage: stonetech66/micro-ride
appVersion: payment-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: POSTGRES_HOST
  value: postgres-payment-service
- name: POSTGRES_PORT
  value: "5432"
- name: REDIS_URL
  value: "redis-payment-service:6379"
- name: NOTIFICATION_SERVICE_HOST
  value: "notification-service:8000"
secrets: 
- name: postgres-payment-service
- name: rabbitmq