appName: ride-service
replicaCount: 1
isConsumer: true
appType: consumer
appScript: "./consumer.sh"
appImage: stonetech66/micro-ride
appVersion: ride-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: POSTGRES_HOST
  value: postgres-ride-service-postgresql
- name: POSTGRES_USER
  value: postgres
- name: POSTGRES_DB
  value: postgres
- name: POSTGRES_PORT
  value: "5432"
- name: REDIS_HOST
  value: "redis-ride-service:6379"
- name: NOTIFICATION_SERVICE_HOST
  value: "notification-service:8000"
- name: RABBITMQ_DEFAULT_USER
  value: guest
- name: RABBITMQ_DEFAULT_PASS
  value: guest
otherSecrets:
- name: POSTGRES_PASSWORD
  secretName: postgres-ride-service-postgresql
  secretKey: postgres-password
- name: WEBSOCKET_SECRET_KEY
  secretName: notification-service
  secretKey: WEBSOCKET_SECRET_KEY
