appName: tracking-service
replicaCount: 1
isConsumer: true
appType: consumer
appScript: "./consumer.sh"
appImage: stonetech66/micro-ride
appVersion: tracking-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: RABBITMQ_DEFAULT_USER
  value: guest
- name: RABBITMQ_DEFAULT_PASS
  value: guest
- name: MONGO_HOST
  value: mongo-tracking-service-mongodb
- name: MONGO_PORT
  value: "27017"
- name: MONGO_ROOT_USERNAME
  value: root
- name: REDIS_HOST
  value: "redis-tracking-service:6379"
otherSecrets:
- name: MONGO_ROOT_PASSWORD
  secretName: mongo-tracking-service-mongodb
  secretKey: mongodb-root-password
