appName: tracking-service
replicaCount: 1
isConsumer: true
appType: consumer
appScript: "./consumer.sh"
appImage: stonetech66/micro-ride
appVersion: tracking-service
containerEnvVars:
- name: RABBITMQ_HOST
  value: rabbitmq
- name: RABBITMQ_PORT
  value: "5672"
- name: MONGO_HOST
  value: mongo-tracking-service
- name: MONGO_PORT
  value: "27017"
- name: REDIS_HOST
  value: "redis-tracking-service:6379"
secrets: 
- name: mongo-tracking-service
- name: rabbitmq