repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: redis-user-account-service
    chart: ../charts/redis
    values:
      - ../values/redis/user-account-service.yaml


  - name: postgres-user-account-service
    chart: bitnami/postgresql
    values:
      - ../values/postgres/user-account-service.yaml
    wait: true

  - name: user-account-service
    chart: ../charts/MicroRide
    values:
      - ../values/microride/user-account-service.yaml



