releases:
  - name: redis-ride-service
    chart: ../charts/redis
    values:
      - ../values/redis/ride-service.yaml


  - name: postgres-ride-service
    chart: bitnami/postgresql
    values:
      - ../values/postgres/ride-service.yaml
    wait: true


  - name: consumer-ride-service
    chart: ../charts/MicroRide
    values:
      - ../values/consumer/ride-service.yaml


  - name: ride-service
    chart: ../charts/MicroRide
    values:
      - ../values/microride/ride-service.yaml


