name: micro-ride-nginx
services:
  - path: /user-account-service(/|$)(.*)
    pathType: Prefix
    svcName: user-account-service
    svcPort: 8000
  - path: /ride-service(/|$)(.*)
    pathType: Prefix
    svcName: ride-service
    svcPort: 8000
  - path: /driver-service(/|$)(.*) 
    pathType: Prefix
    svcName: driver-service
    svcPort: 8000
  - path: /notification-service(/|$)(.*)
    pathType: Prefix
    svcName: notification-service
    svcPort: 8000
  - path: /tracking-service(/|$)(.*) 
    pathType: Prefix
    svcName: tracking-service
    svcPort: 8000
  - path: /payment-servive(/|$)(.*)
    pathType: Prefix
    svcName: payment-service
    svcPort: 8000
